### ISSUE TITLE
Can we get the portfolio Beta Weighted Delta and EXT? 

### ISSUE THREAD

**Issue by rohita77** [tastytrade/tastytrade-api-js#10]

**Comment by dmoss18** [comment]
@rohita77 At this time the scope of this package is just to provide an easy way to hit the public API endpoints, connect to the market data streamer, and connect to the account streamer. You can view your portfolio beta weighted delta on the tastytrade desktop application
https://support.tastyworks.com/support/solutions/articles/43000522492-beta-weighting-your-portfolio-to-a-symbol
