### ISSUE TITLE
Data streaming throttling with "acceptAggregationPeriod"

### ISSUE THREAD

**Issue by dirkdirk** [tastytrade/tastytrade-api-js#14]
Hopefully I just missed it but there does not seem to be a way to throttle data streaming.

The [dxfeed docs](https://demo.dxfeed.com/dxlink-ws/debug/#/protocol) mentions a FEED_SETUP Configuration message but I can't seem to find it in tastytrade-api-js.

Any ideas on how to throttle data steam?

**Comment by dmoss18** [comment]
@dirkdirk DxFeed has their own javascript sdk now. I recommend using it
https://github.com/dxFeed/dxLink/blob/main/dxlink-javascript/dxlink-api/README.md

We will be deprecating MarketDataStreamer in the next release.
