### ISSUE TITLE
Browser Support for JS SDK

### ISSUE THREAD

**Issue by osdevisnot** [tastytrade/tastytrade-api-js#18]
I am attempting to use the SDK client in browser environment. However, this results in below errors:

![image](https://github.com/tastytrade/tastytrade-api-js/assets/802242/90244608-3b8e-4dd0-9aa9-59d723621eec)

Can we please author this SDK in a manner that is compatible with both node.js and browser?

If the is willing to support this feature, I can even attempt to submit a PR to that effect.

**Comment by dmoss18** [comment]
Yes we should be supporting both. I'll take a look at this. Thank you for bringing it up.

**Comment by osdevisnot** [comment]
Thank you @dmoss18. Looks like this was introduced in [`f14d2e5` (#6)](https://github.com/tastytrade/tastytrade-api-js/pull/6/commits/f14d2e5283ac514459bd0212bb2a3bc543928afa). This PR tried to enforce the minimum version for TLS to  1.2, however our node support target is `>=20.0.0`, where the default version is already 1.2 as [documented in the node docs](https://nodejs.org/docs/latest-v20.x/api/tls.html#tlsdefault_min_version).

**Comment by dmoss18** [comment]
@osdevisnot I have a branch up [here](https://github.com/tastytrade/tastytrade-api-js/tree/https-browser-fix). Try it and lmk if it helps.

**Comment by osdevisnot** [comment]
It helps; but I think we might need to find a better solution to browser vs node compatibility scene. For eg: the try catch approach in https://github.com/tastytrade/tastytrade-api-js/pull/24 still results in warnings as noted https://github.com/tastytrade/tastytrade-api-js/pull/24#pullrequestreview-1879040448; mainly because we still import `https` and attempt to use `https.Agent` which is not supported in browser environments. I also created a separate issue https://github.com/tastytrade/tastytrade-api-js/issues/25#issue-2133217745 which should really be part of this one.

**Comment by dmoss18** [comment]
@osdevisnot I have merged PRs for the issues you mentioned. Please confirm that this issue is resolved and I will close and publish a new version of the package.

**Comment by osdevisnot** [comment]
This issue is fixed. However I forgot to add one change which should really be part of #19. I will create a separate PR for that soon.
