### ISSUE TITLE
Streaming Account Connect Returning Not Implemented

### ISSUE THREAD

**Issue by m1771vw** [tastytrade/tastytrade-api-js#36]
Hi there,

I'm trying to stream account data.
I'm working in the Sandbox environment at the moment.
I'm implementing a Typescript, Node, Express server. I'm not using the Tasty Trade JS Library, am using regular webhooks.

I send in this:
```
Added to JSON and sending: {
  action: 'connect',
  value: '5W.....',
  'request-id': 4,
  source: 'tastytrade-api-js-sdk',
  'auth-token': 'hS-tazdJq3a5Bus-...'
}
```
I'm getting this error:

```
HandleOneMessage JSON: {
  status: 'error',
  action: 'connect',
  'web-socket-session-id': 'c69d0c31',
  message: 'not-implemented',
  'request-id': 4
}
```

I have tried the Tasty Trade API JS website example as well and I also get this:
```
{
    "status": "error",
    "action": "connect",
    "web-socket-session-id": "6964b9ef",
    "message": "not-implemented",
    "request-id": 2
}
```

Is the Account Streaming not available right now? I know Tasty Trade is going through some API changes.

**Comment by m1771vw** [comment]
I found out you have to do the connection first and then send a heartbeat. 

I would like to keep this issue open or maybe a different one needs to be opened to fix the Tasty Trade Javascript example?

**Comment by dmoss18** [comment]
@m1771vw Thanks for the issue. We've updated our documentation here https://developer.tastytrade.com/streaming-account-data/#getting-started
