### ISSUE TITLE
Option to set custom logger

### ISSUE THREAD

**Issue by markabrahams** [tastytrade/tastytrade-api-js#43]
Hi team

Thanks for the SDK - I've been using it to good effect to date!

One request I have is that I already have a logger class that does log filtering, structured logging, etc.  I notice that logging (`logger.info` and `logger.warn` specifically) only occurs in the AccountStreamer class, and by way of a statically set logger:

`private readonly logger = console`

Would you consider adding an option for the library to receive a `logger` object and use that in the library for logging as an optional alternative to `console`?  Just something that implements a simple/standard logging interface i.e. functions for trace, debug, info, warn, and error?

A related request is an option to be able to suppress the heartbeat messages that clutter the logs:

```
{
  status: 'ok',
  action: 'heartbeat',
  'web-socket-session-id': 'beea1e13',
  'request-id': 277
}
Scheduling heartbeat with interval:  20000
```

with a custom logger being a nice solution to this as well.

**Comment by dmoss18** [comment]
@markabrahams yeah we can get that added for you. Sorry for the delayed response. It's a good idea.

**Comment by markabrahams** [comment]
Great thanks @dmoss18 - yes I'm thinking along those exact lines!  I can put together a PR for this.

**Comment by dmoss18** [comment]
@markabrahams version 5.0.0 supports custom loggers
