### ISSUE TITLE
Unable to subscribe to equity option quotes

### ISSUE THREAD

**Issue by dmoss18** [tastytrade/tastytrade-api-js#7]
The api quote token only has equities market data available to it. Subscribing to other instruments types via dxLink (equity options, future options, futures) doesn't return any data.

We are aware of the issue and are working with DxFeed to resolve it. Any developments will be posted here.

**Comment by dirkdirk** [comment]
How's the progress going on this front?

**Comment by dmoss18** [comment]
@dirkdirk Unfortunately there is no progress to report yet. We are still working on it. Distributing quote data is something that puts tastytrade at some risk of breeching licensing agreements, especially if they were to make it available to all users with API access. tastytrade has no control over what API users do with those quotes, which poses a real possibility that abusers could use the data to source their own proprietary projects.

For the time being, I recommend sourcing quote data elsewhere if you absolutely need it.

**Comment by dirkdirk** [comment]
@dmoss18  Thanks for the quick reply and the clear explanation.  

I'm an individual trader and am only using a small amount of data to manage my trades.  Can you or anyone recommend a reasonably priced quote data source for a small fry like me?  

(I'm currently using MarketData but their "real-time" data differs wildly from what ToS reports.  I was hoping switching to Tasty's API would solve this issue.  At least with Tasty I can stream my orders and positions ... so that solves the manual data input pain point.  As of this post, Schwab has yet to turn back on ToS's API and they have no time horizon of when that will happen.)

So if anyone can recommend a realtime quote streamer I would highly appreciate it.

**Comment by dirkdirk** [comment]
@dmoss18 What if quote data via the API for equity options, future options, futures are limited to only positions the user is in?  That way the quote data is severely limited and really only useful to the user.

**Comment by dmoss18** [comment]
@dirkdirk It's a good idea, but tastytrade's market data vendor, DxFeed, doesn't have any notion of tastytrade account positions, so they wouldn't be able to enforce that on their end.

Open interest and greeks are both part of specific market events ([Greeks](https://docs.dxfeed.com/dxfeed/api/com/dxfeed/event/option/Greeks.html) and [Summary](https://docs.dxfeed.com/dxfeed/api/com/dxfeed/event/market/Summary.html), respectively). The licensing/distribution concerns still apply to those. Sorry I don't have a better answer for you at the moment.

**Comment by geofflittle** [comment]
[This issue](https://github.com/tastytrade/tastytrade-api-js/issues/5) mentions using a delayed quotes endpoint (wss://tasty-demo-ws.dxfeed.com/delayed). Is this a viable, intermittent workaround? How delayed are these quotes?

**Comment by topvis** [comment]
Quote for index (e.g., SPX, NDX) does not work either.

**Comment by dmoss18** [comment]
Good news, you should now be able to subscribe to equity option quotes using the token returned from the `GET /api-quote-tokens` endpoint.

**Comment by geofflittle** [comment]
@dmoss18 The original comment of this issue says

> Subscribing to other instruments types via dxLink (equity options, future options, futures) doesn't return any data.

Does the resolution of this issue mean futures options are now available via dxLink?

**Comment by IV2KBMoFxYIA** [comment]
> Good news, you should now be able to subscribe to equity option quotes using the token returned from the `GET /api-quote-tokens` endpoint.

same as previous. can we get futures options data now? i dont want to go through the trouble of working through it if it doesn't work.

**Comment by zlymeda** [comment]
I tested it and can get `equity option` quotes and `future options` quotes.

interestingly, I can get option quotes for `SPX`, but not for `SPX` itself.

`greeks` seem not to work

**Comment by dirkdirk** [comment]
> interestingly, I can get option quotes for `SPX`, but not for `SPX` itself.

Try SPXW ... ?
https://www.marketdata.app/education/options/spx-vs-spxw-options/

**Comment by IV2KBMoFxYIA** [comment]
> Good news, you should now be able to subscribe to equity option quotes using the token returned from the `GET /api-quote-tokens` endpoint.

will this endpoint ever have futures options greeks on it?

**Comment by dmoss18** [comment]
@IV2KBMoFxYIA Still working on greeks for this. I'll post here with more info when I have it.
